In [1]:
############################################################################################################################
# Nitin Jindal and Bing Liu. "Identifying Comparative Sentences in Text Documents" Proceedings of
# the 29th Annual International ACM SIGIR Conference on Research & Development on Information
# Retrieval (SIGIR-06), Seattle 2006.
############################################################################################################################

comparison = [('comparison', 'more'),
              ('comparison', 'less'),
              ('comparison', 'better'),
              ('comparison', 'worse'),
              ('comparison', 'further'),
              ('comparison', 'farther'),
              ('comparison', 'beat'),
              ('comparison', 'defeat'),
              ('comparison', 'equal'),
              ('comparison', 'equally'),
              ('comparison', 'lead'),
              ('comparison', 'destroy'),
              ('comparison', 'decimate'),
              ('comparison', 'kill'),
              ('comparison', 'obliterate'),
              ('comparison', 'outclass'),
              ('comparison', 'out class'),
              ('comparison', 'out-class'),
              ('comparison', 'outdo'),
              ('comparison', 'outperform'),
              ('comparison', 'outplay'),
              ('comparison', 'overtake'),
              ('comparison', 'over take'),
              ('comparison', 'over-take'),
              ('comparison', 'smack'),
              ('comparison', 'subdue'),
              ('comparison', 'subpar'),
              ('comparison', 'surpass'),
              ('comparison', 'top'),
              ('comparison', 'trump'),
              ('comparison', 'unmated'),
              ('comparison', 'win'),
              ('comparison', 'ahead of'),
              ('comparison', 'blow away'),
              ('comparison', 'blow out of water'),
              ('comparison', 'favor'),
              ('comparison', 'cannot race against'),
              ('comparison', 'cannot compete with'),
              ('comparison', 'compare'),
              ('comparison', 'in comparison'),
              ('comparison', 'no comparison'),
              ('comparison', 'cannot compare'),
              ('comparison', 'inferior to'),
              ('comparison', 'superior to'),
              ('comparison', 'lag behind'),
              ('comparison', 'lose'),
              ('comparison', 'number one'),
              ('comparison', 'on par'),
              ('comparison', 'on a par'),
              ('comparison', 'not like'),
              ('comparison', 'nothing like'),
              ('comparison', 'unlike'),
              ('comparison', 'prefer'),
              ('comparison', 'suck against'),
              ('comparison', 'vulnerable to'),
              ('comparison', 'up against'),
              ('comparison', 'take over'),
              ('comparison', 'win against'),
              ('comparison', 'win against'),
              ('comparison', 'equivalent'),
              ('comparison', 'identical'),
              ('comparison', 'same as'),
              ('comparison', 'similar'),
              ('comparison', 'dissimilar'),
              ('comparison', 'match'),
              ('comparison', 'unequal'),
              ('comparison', 'not alike')
]

In [2]:
############################################################################################################################
# Minqing Hu and Bing Liu. "Mining and Summarizing Customer Reviews." 
# Proceedings of the ACM SIGKDD International Conference on Knowledge 
# Discovery and Data Mining (KDD-2004), Aug 22-25, 2004, Seattle, 
# Washington, USA, 
############################################################################################################################

def list_of_tuple(list_in, description):
    list_out = list()
    for word in list_in:
        list_out.append((description, word)) 
    return list_out
    

positive = open("positive-words.txt", "r")
positive_words = positive.read().splitlines()
positive = list_of_tuple(positive_words, "positive")
    
negative = open("negative-words.txt", "r")
negative_words = negative.read().splitlines()
negative = list_of_tuple(negative_words, "negative")

In [3]:
stop_words =  ["i", "me", "my", "myself", "we", "our", "ours", "ourselves", "you", "your", "yours", "yourself", "yourselves", "he", "him", "his", "himself", "she", "her", "hers", "herself", "it", "its", "itself", "they", "them", "their", "theirs", "themselves", "what", "which", "who", "whom", "this", "that", "these", "those", "am", "is", "are", "was", "were", "be", "been", "being", "have", "has", "had", "having", "do", "does", "did", "doing", "a", "an", "the", "and", "but", "if", "or", "because", "as", "until", "while", "of", "at", "by", "for", "with", "about", "against", "between", "into", "through", "during", "before", "after", "above", "below", "to", "from", "up", "down", "in", "out", "on", "off", "over", "under", "again", "further", "then", "once", "here", "there", "when", "where", "why", "how", "all", "any", "both", "each", "few", "more", "most", "other", "some", "such", "no", "nor", "not", "only", "own", "same", "so", "than", "too", "very", "s", "t", "can", "will", "just", "don", "should", "now"]
stop = list_of_tuple(stop_words, "stop")

In [5]:
library = tuple(comparison + positive + negative + stop)
library[1:10]

(('comparison', 'less'),
 ('comparison', 'better'),
 ('comparison', 'worse'),
 ('comparison', 'further'),
 ('comparison', 'farther'),
 ('comparison', 'beat'),
 ('comparison', 'defeat'),
 ('comparison', 'equal'),
 ('comparison', 'equally'))

In [6]:
import pandas as pd
tt_lexicon_1 = pd.read_excel("Table tennis lexicon.xlsx", usecols = "A:B").dropna()
tt_lexicon_2 = pd.read_excel("Table tennis lexicon.xlsx", usecols = "D:E").dropna()
tt_lexicon_2.columns = tt_lexicon_1.columns
tt_colloquial = tt_lexicon_1.append(tt_lexicon_2)
tt_colloquial

       colloquial                translation
0   t05, 05, t-05                 Tenergy 05
1   t64, 64, t-64                 Tenergy 64
2   t25, 25, t-25                 Tenergy 25
3       MX-P, mxp             Evolution MX-P
4              h3                Hurricane 3
5              h8                Hurricane 8
6             h39                Hurricane 3
7             h38                Hurricane 3
8             h45                        729
9             h47                        729
10            h49                        729
11            STN     Sanwei National Target
12         h3 neo            Hurricane 3 Neo
13          gearz   Gambler X3 Diamond Gearz
14      mech-tech  Gambler Mech-Tek Predator
15       mech-tek  Gambler Mech-Tek Predator
16         sevens         Gambler Sevens Pro
17           ak47                 Palio AK47
18     Red Dragon     Three Sword Red Dragon
19   Green Dragon    KTL Pro XT Green Dragon
20           999T                 Super 999T
21      EL-P, elp      Tibhar Evolution EL-P
22      EL-S, els       Tibhar Evolution ELS
23            400            Joola Maxxx 400
24      FX-P, fxp      Tibhar Evolution FX-P
25          t05fx              Tenergy 05 FX
26             m2          Donic Bluefire M2
27             R7                    Rakza 7
28         r7soft               Rakza 7 Soft
29   t05-FX, 05fx              Tenergy 05 FX
30             O7             Xiom Omega VII
31    O7A/O7E/O7T           Asia/Europe/Tour
33             s2             Donic Acuda S2
34             HD             Andro Hexer HD
0              bh                   backhand
1              fh                   forehand
2              bs                blue sponge
3              bd        blue diamond sponge